### ISSUE TITLE
adding syntactic sugar for --keep-going

### ISSUE THREAD

**Issue by wolfwood** [sakaki-/emtee#1]
emtee is AMAZING! It's an excellent approach to tackle a thorny problem, by treating emerge as a black box.

If anything, your README is too modest:  I went from 7 mins for a failing `emerge -puvND @world`, or 19 minutes for a successful `emerge -puvND --backtrack=30 --autounmask-backtrack=y @world` to 30 sec for `emtee -p`.

but I was wondering if I could convince you to add --keep-going by default, with a switch to disable, or at lease a flag to enable it.  I feel that this behavior is a much better experience, and since portage preserves dependent libraries for un-upgraded packages there is little downside to allowing the upgrade to go as far as it can.  of course, I understand that I can use `-E--keep-going` but since you've added convenience flags for -a, -p, etc. I thought this was a good candidate too.

the main issue that prevented emerge from having a more convenient shorthand is that `-k` was already taken. since `--usepkg` is not directly relevant to emtee, perhaps you would be willing to use `-K` to disable `--keep-going`, or `-k` to enable if you would prefer not to have it be a default. otherwise, I'm not sure what a good letter to use would be. `-g` is also in use by emerge, unfortunately.

in any case, thank you for the effort you put in to not just creating, but thoroughly documenting this tool.

**Comment by sakaki-** [comment]
Hi @wolfwood,

thanks for the nice feedback ^-^

There aren't too many people using this tool yet, as I haven't really publicised it, so adding an extra default arg shouldn't cause any real breakage (I use the `--keep-going` flag myself most times).

I'll have a look at adding something over the next few weeks.

Best, sakaki

**Comment by wolfwood** [comment]
thanks!
